// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIEMS.Data;

#nullable disable

namespace EMS_Phase3__FinalProject01.Migrations
{
    [DbContext(typeof(EMSDbContext))]
    [Migration("20240212110928_rendomigration")]
    partial class rendomigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPIEMS.Models.DeptMaster", b =>
                {
                    b.Property<int>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptCode"), 1L, 1);

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptCode");

                    b.ToTable("DeptMaster");

                    b.HasData(
                        new
                        {
                            DeptCode = 1,
                            DeptName = "CSE"
                        },
                        new
                        {
                            DeptCode = 2,
                            DeptName = "MPC"
                        },
                        new
                        {
                            DeptCode = 3,
                            DeptName = "MECH"
                        },
                        new
                        {
                            DeptCode = 4,
                            DeptName = "ECE"
                        },
                        new
                        {
                            DeptCode = 5,
                            DeptName = "IT"
                        });
                });

            modelBuilder.Entity("WebAPIEMS.Models.EmpProfile", b =>
                {
                    b.Property<int>("EmpCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpCode"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptCode")
                        .HasColumnType("int");

                    b.Property<int?>("DeptMasterDeptCode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCode");

                    b.HasIndex("DeptMasterDeptCode");

                    b.ToTable("EmpProfile");

                    b.HasData(
                        new
                        {
                            EmpCode = 101,
                            DateOfBirth = new DateTime(2004, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 1,
                            Email = "RamaaLoadethalra@gmail.com",
                            EmpName = "Ramana"
                        },
                        new
                        {
                            EmpCode = 102,
                            DateOfBirth = new DateTime(1678, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 2,
                            Email = "vickyjain@outlook.com",
                            EmpName = "Vikas"
                        },
                        new
                        {
                            EmpCode = 103,
                            DateOfBirth = new DateTime(2008, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 3,
                            Email = "vikramrathore@yahoo.com",
                            EmpName = "Vikram Rathore"
                        },
                        new
                        {
                            EmpCode = 104,
                            DateOfBirth = new DateTime(1999, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 4,
                            Email = "loveyou3000@gmail.com",
                            EmpName = "Pepper pots"
                        },
                        new
                        {
                            EmpCode = 105,
                            DateOfBirth = new DateTime(2006, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 5,
                            Email = "captainamerica@heroo.com",
                            EmpName = "chris Hemsworth"
                        });
                });

            modelBuilder.Entity("WebAPIEMS.Models.EmpProfile", b =>
                {
                    b.HasOne("WebAPIEMS.Models.DeptMaster", "DeptMaster")
                        .WithMany("EmpProfiles")
                        .HasForeignKey("DeptMasterDeptCode");

                    b.Navigation("DeptMaster");
                });

            modelBuilder.Entity("WebAPIEMS.Models.DeptMaster", b =>
                {
                    b.Navigation("EmpProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
